import * as THREE from "three";

// =============================================================================
// Cloud vertical-profile LUT (CLOUD_TYPES_PLAN.md Phase 2, §4.2).
//
// WHAT THIS REPLACES: the 3 analytic curves + 2 smoothsteps in
// cloudShared.cloudHeightProfile. Those give exactly THREE discrete shapes
// (stratus / stratocumulus / cumulus) mixed at a single 0.5 pivot → the
// "two looks" problem and a binary border at the pivot. This LUT is a
// CONTINUOUS family of 64 distinct vertical anatomies indexed by the
// convectivity axis (map channel G) — every convectivity value gets its own
// fitted genus shape, so type varies continuously with no border.
//
// LAYOUT: 64×64 single-channel (R8) DataTexture.
//   u (x, width)  = altNorm ∈ [0,1]  — altitude normalized to the column's
//                   OWN [baseN, topN] span (the km-anchoring the shader does;
//                   see cloudShared). u=0 is the cloud base, u=1 the top.
//   v (y, height) = convectivity ∈ [0,1] — 0 = layered/stratiform (St/Sc/As),
//                   1 = deep convective (Cb). THE type axis.
//   value         = vertical density fraction ∈ [0,1] at that (altNorm, conv).
//
// The shader multiplies this by coverage → dimensional profile, then the
// Nubis-form value erosion carves it (unchanged composition form, §4.2).
//
// ── RED-TEAM BLOCKERS (do not skip; each caused a documented bug class) ──
//  1. EVERY ROW IS EXACTLY 0 AT altNorm 0 AND 1, peak strictly interior.
//     altNorm saturates at the column boundaries, so a row nonzero at u=1
//     would extrude every such column from its top to the slab CEILING
//     (and u=0 to the floor) — the sliced-tops / floor-extrusion regression.
//     Enforced structurally by the row formula (rise·top both hit 0 at the
//     ends) AND clamped + asserted below.
//  2. ALL 64 ROWS ARE GENERATED BY INTERPOLATING ANATOMY PARAMETERS
//     (base-ramp width, top-fade start, dome exponent, plateau) between the
//     genus anchors — the Nubis-2017 endpoint-slide evaluated at 64 samples.
//     We do NOT author sparse anchor rows and let texture filtering blend
//     them: blending two dissimilar FINISHED curves gives two-bump
//     half-amplitude profiles the erosion deletes → the binary border returns
//     at row midpoints. Because adjacent rows here differ only by a small
//     parameter step, bilinear filtering across convectivity only ever bridges
//     near-identical neighbours (safe).
//
// The row shape (canonical cloud density over its own [base,top] span):
//   rise  = smootherstep(0, baseRampW, altNorm)     // condensation base ramp
//   fadeX = clamp((altNorm − fadeStart)/(1 − fadeStart), 0, 1)
//   top   = 1 − fadeX^domeExp                        // cloud-top fade / dome
//   value = plateau · rise · top
// rise=0 at altNorm 0; top=0 at altNorm 1 → boundary-zero by construction.
//
// GENUS ANCHORS (v = convectivity), anatomy PARAMETERS (not curves):
//   v=0.00  St  — soft base, late high fade, flat-topped sheet (domeExp 3 =
//                 holds near 1 then drops). Physical thinness comes from the
//                 shader placing baseN just below topN (thin span), so the
//                 sheet fills its thin span. Peak interior.
//   v=0.40  Sc  — broken cellular slab, moderate base, softer earlier top.
//   v=0.70  Cu  — the PORTED existing cumulus anatomy: SHARP low base
//                 (~smoothstep 0.04–0.16 equiv → baseRampW 0.08) + PARABOLIC
//                 dome (domeExp 2, the documented rounded-top fix). Biggest
//                 dome (lowest fadeStart) → tall rounded tower.
//   v=1.00  Cb  — full-depth tower body: hard base, near-full mid density,
//                 slight taper near the top (anvil is a separate modifier,
//                 §4.4 — NOT baked into the row).
// =============================================================================

const SIZE = 64; // 64×64 per §4.2 (altNorm ×64 resolves the base ramp ~5 texels)

// ── Genus anchors: (convectivity, anatomy params). Piecewise-linear in c. ──
// Fitted by eye against the anatomy walkthrough (cloud_shape_anatomy.md); the
// EXACT numbers are tunable — the STRUCTURE (monotone base sharpening toward
// convective, biggest dome at Cu, boundary-zero) is what matters for R1.
type RowParams = {
  baseRampW: number; // width of the bottom condensation ramp (altNorm units)
  fadeStart: number; // altNorm where the cloud-top fade begins
  domeExp: number; //   exponent of the top fade 1 − x^exp (2 = parabolic dome)
  plateau: number; //   peak density in the mid-band
  waist: number; //     mid-column pinch depth (T2/§4.11, Blackrack Cb
  //                    silhouette: narrow waist + re-widened glaciated top).
  //                    Multiplicative ≤1 → boundary-zero invariant unaffected.
};

const ANCHORS: { c: number; p: RowParams }[] = [
  // prettier-ignore
  { c: 0.0, p: { baseRampW: 0.2, fadeStart: 0.72, domeExp: 3.0, plateau: 0.92, waist: 0 } }, // St
  // prettier-ignore
  { c: 0.4, p: { baseRampW: 0.14, fadeStart: 0.6, domeExp: 2.4, plateau: 0.96, waist: 0 } }, // Sc
  // prettier-ignore
  { c: 0.7, p: { baseRampW: 0.08, fadeStart: 0.48, domeExp: 2.0, plateau: 1.0, waist: 0 } }, // Cu
  // Cb (T2): fadeStart raised 0.62→0.70 (top RE-WIDEN — density holds fuller
  // toward the glaciated shield before the dome fade) + a mild mid waist →
  // the classic anvil silhouette even before the coverage-pow spread.
  // prettier-ignore
  { c: 1.0, p: { baseRampW: 0.05, fadeStart: 0.7, domeExp: 2.6, plateau: 1.0, waist: 0.25 } }, // Cb
];

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

function clamp01(x: number): number {
  return x < 0 ? 0 : x > 1 ? 1 : x;
}

function smootherstep01(t: number): number {
  const x = clamp01(t);
  return x * x * x * (x * (x * 6 - 15) + 10);
}

// Interpolate the anatomy parameters at an arbitrary convectivity (INVARIANT 2:
// every one of the 64 rows comes from HERE — parameter interpolation — never
// from filtering two finished curves).
function paramsAt(convectivity: number): RowParams {
  const c = clamp01(convectivity);
  // Find the anchor segment [lo, hi] bracketing c.
  let lo = ANCHORS[0];
  let hi = ANCHORS[ANCHORS.length - 1];
  for (let k = 0; k < ANCHORS.length - 1; k++) {
    if (c >= ANCHORS[k].c && c <= ANCHORS[k + 1].c) {
      lo = ANCHORS[k];
      hi = ANCHORS[k + 1];
      break;
    }
  }
  const span = hi.c - lo.c;
  const t = span > 1e-6 ? (c - lo.c) / span : 0;
  return {
    baseRampW: lerp(lo.p.baseRampW, hi.p.baseRampW, t),
    fadeStart: lerp(lo.p.fadeStart, hi.p.fadeStart, t),
    domeExp: lerp(lo.p.domeExp, hi.p.domeExp, t),
    plateau: lerp(lo.p.plateau, hi.p.plateau, t),
    waist: lerp(lo.p.waist, hi.p.waist, t),
  };
}

/**
 * The canonical vertical density at (altNorm, convectivity) ∈ [0,1]². Pure JS,
 * the SAME function the LUT generator bakes per texel — exported so the
 * inspector (/dev/cloud-profile) plots exactly what the shader samples.
 */
export function profileLUTValue(altNorm: number, convectivity: number): number {
  const a = clamp01(altNorm);
  const { baseRampW, fadeStart, domeExp, plateau, waist } =
    paramsAt(convectivity);
  const rise = smootherstep01(a / Math.max(baseRampW, 1e-4));
  const fadeX = clamp01((a - fadeStart) / Math.max(1 - fadeStart, 1e-4));
  const top = 1 - Math.pow(fadeX, domeExp);
  // Mid-column waist (Cb silhouette, T2): a smooth pinch bump centered at
  // altNorm 0.45, ±0.3 wide. Multiplicative ≤1 → boundary-zero + interior-peak
  // invariants hold for any waist ∈ [0,1).
  const pinch =
    waist > 0
      ? 1 - waist * smootherstep01(1 - Math.abs(a - 0.45) / 0.3)
      : 1;
  return plateau * rise * top * pinch;
}

let cached: THREE.DataTexture | null = null;

/**
 * Process-lifetime singleton (getAtmosphereLUTs / getStbnTexture / weatherMapV2
 * pattern — NOT routed through the per-tier texture records; never reassigned
 * on a live material). Cheap: 64×64 = 4096 texels generated once.
 *
 * NO MIPMAPS + LinearFilter: altNorm and convectivity are NOT screen-space
 * coordinates, so mip selection from screen-space UV derivatives would be
 * meaningless (and could blur adjacent genera). All consumers sample L0.
 */
export function getCloudProfileLUT(): THREE.DataTexture {
  if (cached) return cached;

  const data = new Uint8Array(SIZE * SIZE); // R8, one byte per texel
  for (let j = 0; j < SIZE; j++) {
    const convectivity = j / (SIZE - 1); // v: 0 stratiform → 1 convective
    for (let i = 0; i < SIZE; i++) {
      const altNorm = i / (SIZE - 1); // u: 0 base → 1 top
      let val = profileLUTValue(altNorm, convectivity);
      // INVARIANT 1: force the two boundary texels of every row to exactly 0
      // (belt-and-suspenders over the structural guarantee — a rounding error
      // at u=1 would extrude the whole column to the slab ceiling).
      if (i === 0 || i === SIZE - 1) val = 0;
      data[j * SIZE + i] = Math.round(clamp01(val) * 255);
    }
  }

  // Automated boundary-zero check (INVARIANT 1) — warn loudly if a future
  // parameter edit ever breaks it rather than shipping ceiling extrusion.
  let boundaryMax = 0;
  for (let j = 0; j < SIZE; j++) {
    boundaryMax = Math.max(boundaryMax, data[j * SIZE], data[j * SIZE + SIZE - 1]);
  }
  if (boundaryMax !== 0) {
    console.error(
      `[cloudProfileLUT] BOUNDARY-ZERO INVARIANT VIOLATED (max edge texel ${boundaryMax}) — columns will extrude to the slab ceiling/floor.`,
    );
  }

  const tex = new THREE.DataTexture(
    data,
    SIZE,
    SIZE,
    THREE.RedFormat,
    THREE.UnsignedByteType,
  );
  tex.colorSpace = THREE.NoColorSpace; // data, not colour
  tex.wrapS = THREE.ClampToEdgeWrapping; // altNorm clamps → boundary-zero saturation
  tex.wrapT = THREE.ClampToEdgeWrapping; // convectivity clamps (never wraps)
  tex.minFilter = THREE.LinearFilter;
  tex.magFilter = THREE.LinearFilter;
  tex.generateMipmaps = false;
  tex.needsUpdate = true;
  cached = tex;
  return tex;
}
