/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf -t -s -i -T 
Files: scene.gltf [6.25KB] > scene-transformed.glb [1.27MB] (-20284%)
Author: JazOone (https://sketchfab.com/JazOone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-6164a883f57f4f13938c3c5999bc0e1f
Title: SpaceShip
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Starship_Material003_0: Mesh;
  };
  materials: {
    ["Material.003"]: MeshStandardMaterial;
  };
};

export function ShipOne(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/ships/ShipOne.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.3}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Starship_Material003_0.geometry}
        material={materials["Material.003"]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/ships/ShipOne.glb");
