/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf -t -s -i -T 
Files: scene.gltf [6.25KB] > scene-transformed.glb [1.27MB] (-20284%)
Author: JazOone (https://sketchfab.com/JazOone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-6164a883f57f4f13938c3c5999bc0e1f
Title: SpaceShip
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Mesh, MeshStandardMaterial } from "three";

import { useMemo } from "react";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Starship_Material003_0: Mesh;
  };
  materials: {
    ["Material.003"]: MeshStandardMaterial;
  };
};

// ── Hull emissive on the photometric scale (LIGHTING_PLAN Phase 5) ──────────
// The GLB's baked emissive (lit panels / nozzle interiors) ships at
// emissiveIntensity 1, which MEASURED at 1.11 game units ≈ **6,700 cd/m²** — as
// bright as a sunlit cloud top, on a small ship part, always on regardless of
// throttle (the actual thruster plume is the separate <EngineExhaust>).
//
// That was invisible while exposure was manual, and became load-bearing the
// moment Phase 5 metered on a LINEAR flux mean: an emissive at ~1% of frame
// carried **13× the flux of Neptune's entire 92%-of-frame disc**, dragging
// adaptation 1.7 stops bright and darkening the planet behind it. A flux mean is
// only as good as the emissives — so the emissive gets a physical value rather
// than the meter getting a workaround.
//
// ⚠ 0 FOR NOW, and the reason is not that a glowing hull is wrong. MEASURED at
// 0.03 (≈60 cd/m² peak): in a deep-space frame the hull still carried **99% of
// the metered flux** and owned adaptation outright, so stars vanished. At 0 the
// same frame meters −17 instead of −11.98.
//
// That is not the meter misbehaving — it is the THIRD-PERSON CAMERA problem every
// game with a visible player vehicle hits: the flux mean is physically right, and
// physically your own lit hull *is* the brightest thing in interstellar space, so
// an eye would adapt to it and lose the sky. Games solve this by excluding or
// damping the player vehicle in metering, not by dimming the ship.
//
// ── D26, 2026-08-21: RESOLVED — STAYS 0, for a BETTER reason than the above ──
// The reasoning above ("0 because the meter cannot discount the local scene") has
// EXPIRED: D31's stratified tile metering and the hot-tail compressor
// (`HOT_WEIGHT_FRACTION` 0.02, `MAX_HOT_FLUX_SHARE` 0.3, `HOT_COMPRESS_EXPONENT` 0.5)
// both landed afterwards, and the compressor IS a discount on any small hot region —
// a better formulation than excluding the player, since it also covers the mining
// laser and a close sunlit asteroid.
//
// 🔑 But restoring the emissive was still wrong, on grounds unrelated to the meter:
// **this emissive is the nozzle interior, and it glowed at ZERO THROTTLE.** A thruster
// emitting light while the ship is stationary is incorrect at ANY luminance. The
// dynamic plume is the separate <EngineExhaust>, which does scale with acceleration.
// So 0 here is the physics, not a workaround.
//
// ⚠ AND THE EXPERIMENT THAT WAS MEANT TO SETTLE IT WAS INCONCLUSIVE — how it failed
// is the reusable part: 0.03 and 0.0 returned BYTE-IDENTICAL meter readings, metered
// EV −14.74 with every percentile equal (p05 −16.28 … max −9.18). A 181 cd/m²
// emissive on an in-frame object cannot leave `EV max` at ~2e-4 cd/m², so the value
// was never live: `hull` is memoised on `materials`, and Fast Refresh does not re-run
// that memo. **A constant consumed inside a useMemo needs a FULL RELOAD to test** —
// and two identical readings are evidence of a dead experiment, not of a null result.
//
// ⇒ If the GLB's emissive also covers lit PANELS or indicators (things that SHOULD
// glow at rest), the fix is to split the material or drive the nozzle term from
// throttle — not one compromise value for both. The units are real, so whatever gets
// chosen is a physical statement.
//
// ⇒ MEASURED, and this is where D26 actually lives: the <EngineExhaust> plume drags
// metered EV from −14.74 to −10.3 — **4.4 stops** — while occupying 2% of frame
// weight and carrying ~100% of frame flux, with the compressor already holding back
// ~5.5 stops. The hull was never the problem. See LIGHTING_PLAN D26.
const HULL_EMISSIVE_INTENSITY = 0.0;

export function ShipOne({ children, ...props }: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/ships/ShipOne.glb"
  ) as unknown as GLTFResult;
  // CLONE rather than mutate: useGLTF caches materials per URL, so writing to the
  // hook's material would be a cross-instance side effect during render (and the
  // lint rule is right to object). The clone is memoised on the source material,
  // so it happens once per loaded GLB, not per frame.
  const hull = useMemo(() => {
    const m = materials["Material.003"].clone();
    m.emissiveIntensity = HULL_EMISSIVE_INTENSITY;
    return m;
  }, [materials]);
  return (
    <group {...props} dispose={null} scale={0.3}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Starship_Material003_0.geometry}
        material={hull}
        scale={0.01}
      />
      {children}
    </group>
  );
}

useGLTF.preload("/models/ships/ShipOne.glb");
